on:
  [ push ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
      - name: Install
        run: npm install
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build
      - name: start docker
        run: cd examples/postgresql-docker && docker-compose up -d
      - name: Build
        run: npm run test
